services:

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zum
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
  
  audio-player:
    build:
      context: ./zum-audio-player
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - zum
  
networks:
  zum:
    name: zum-network
