services:

  ### INFRASTRUCTURE

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zum
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
  
  ### SERVICES

  audio-player:
    build:
      context: ./zum-audio-player
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - zum
  
  # voice-controller:
  #   build:
  #     context: ./zum-voice-controller
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - audio-player
  #     - rabbitmq
  #   networks:
  #     - zum
    
  # command-recognition:
  #   build:
  #     context: ./zum-command-recognition
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - voice-controller
  #   networks:
  #     - zum


networks:
  zum:
    name: zum-network
